### ISSUE TITLE
README.md references deadline link

### ISSUE THREAD

**Issue by SimplyAhmazing** [Opentrons/otone_backend#1]
The [README.md](https://github.com/OpenTrons/otone_backend/blob/master/README.md) has a link reference to ["Scripts"](https://github.com/OpenTrons/otone_scripts) which appears to be a non-existent repo. Not sure if repo was relocated elsewhere and link should be updated or if it was altogether removed and link reference should be removed.

**Comment by nwags** [comment]
Scripts is a private repo. We'll be cleaning up these repos shortly and we're looking forward to replacing them entirely with a new code base that is well tested and setup for CI/CD.
