### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by dnhkng** [Opentrons/otone_backend#10]
It would be nice to have at least minimal guidance for running this code on Windows.

i.e. a demo script that performs homing and controls the various axis's etc.

I would like to control a device directly connected to the smoothieboard, using a GUI similar to Printrun for 3D printers. i.e. buttons for moving axis,, homing, and starting scripts.

**Comment by nwags** [comment]
https://github.com/OpenTrons/otone_frontend
